name: Deploy static HTML to Azure Web App - demosistemas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # For Azure login
      contents: read  # For checkout

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_91E12B35D57E4142A39D9D53E08E2F3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B6872FFFF8846AF88EDA43010D78537 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3DDEA8AA92948DAAA3738342EA30A72 }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy static site to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demosistemas'
          slot-name: 'Production'
          package: .
